[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add  =  '''
set background=dark
au MyAuto VimEnter * colorscheme hybrid
'''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source $VIMRCDIR/rc/plugins/lightline.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'nginx.vim'
on_ft = 'nginx'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'xmledit'
on_ft = 'xml'

[[plugins]]
repo = 'theevocater/thrift.vim'
on_ft = 'thrift'

[[plugins]]
repo = 'docker/docker'
rtp = 'contrib/syntax/vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'LeafCage/foldCC.vim'
hook_add = '''
set foldtext=FoldCCText()
'''

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
